name: Remote Workflow Test

on:
  repository_dispatch:
    types: [bump-contracts-version]

jobs:
  bump-contracts-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - run: echo ${{ github.event.client_payload.sha }}
      - run: echo ${{ github.event.client_payload.test }}
