name: Remote Workflow Test

on:
  repository_dispatch:
    types: [bump-contracts-version]

jobs:
  bump-contracts-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.test }}
      - run: go get -u github.com/rtorrero/ci-playground-beta@${{ github.event.client_payload.test }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
